choboishop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    ),
]

choboishop/choboionline/urls.py
from django.urls import path
from . import views


app_name = 'choboionline'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
]

choboishop/choboishop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('choboionline.urls', namespace='choboionline')),
)
urlpatterns += [
    path(
        'payment/webhook/',
        webhooks.stripe_webhook,
        name='stripe-webhook'
    ),
 ]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

choboishop/choboionline/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields


class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200, verbose_name="Category Name"),
        slug=models.SlugField(max_length=200, unique=True, verbose_name="Category Slug"),
    )

    class Meta:
       # ordering = ['name']
       # indexes = [
       #    models.Index(fields=['name']),
       # ]
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """
        Returns the absolute URL for a category instance.
        """
        return reverse(
            'choboionline:product_list_by_category', args=[self.slug]
        )

    def __str__(self):
        """
        Returns a human-readable string representation of the model.
        """
        return self.name


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200),
        slug=models.SlugField(max_length=200),
        description=models.TextField(blank=True)
    )
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE,
        verbose_name="Category"
    )
    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True,
        verbose_name="Product Image"
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name="Price"
    )
    available = models.BooleanField(default=True, verbose_name="Available")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
       # ordering = ['name']
        indexes = [
          #  models.Index(fields=['id', 'slug']),
          #  models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_absolute_url(self):
        """
        Returns the absolute URL for a product instance.
        """
        return reverse('choboionline:product_detail', args=[self.id, self.slug])

    def __str__(self):
        """choboionline:''product_detail', args=[self.id]
        Returns a human-readable string representation of the model.
        """
        return self.name

choboishop/choboionline/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Product
from cart.forms import CartAddProductForm
from .recommender import Recommender


def product_list(request, category_slug=None):
    """
    Display a list of products. Optionally filter by category.

    Args:
        request: The HTTP request object.
        category_slug (str, optional): The slug of the category to filter products by.

    Returns:
        HttpResponse: Rendered HTML page with the list of products.
    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(
            Category,
            translations__language_code=language,
            translations__slug=category_slug)
        products = products.filter(category=category)

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
        }
    )


def product_detail(request, id, slug):
    """
    Display details of a single product.

    Args:
        request: The HTTP request object.
        id (int): The ID of the product.
        slug (str): The slug of the product.

    Returns:
        HttpResponse: Rendered HTML page with product details.
    """
    language = request.LANGUAGE_CODE
    product = get_object_or_404(
        Product,
        id=id,
        translations__language_code=language,
        translations__slug=slug,
        available=True
    )
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(
        request,
        'shop/product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
            'recommended_products': recommended_products
        }
    )

choboishop/choboionline/templates/shop/base.html
<!DOCTYPE html>
{% load i18n static %}
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}{% translate "Choboishop" %}{% endblock %}</title>
<link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo">{% translate "Choboishop" %}</a>
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="languages">
        <p>{% translate "Language" %}:</p>
        <ul class="languages">
            {% for language in languages %}
                <li>
                    <a href="/{{ language.code }}/"
                       {% if language.code == LANGUAGE_CODE %} class="selected" {% endif %}>
                        {{ language.name_local }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div id="subheader">
<div class="cart">
{% with total_items=cart|length %}
{% if total_items > 0 %}
{% translate "Your cart" %}:
<a href="{% url 'cart:cart_detail' %}">
    {% blocktranslate with total=cart.get_total_price count items=total_items %}
        {{ items }} item, ${{ total }}
    {% plural %}
        {{ items }} items, ${{ total }}
    {% endblocktranslate %}
</a>
{% elif not order %}
    {% translate "Your cart is empty." %}
{% endif %}
    {% endwith %}
</div>
</div>
<div id="content">
{% block content %}
{% endblock %}
</div>
<br>


<footer style="text-align: center; padding: none; background-color: white; color: red; width: 100%;">
    <p>&copy; 2025 Choboishop Ecommerce System. All Rights Reserved.</p>
</footer>
</body>
</html>